// <auto-generated />
using Blog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog
{
    [DbContext(typeof(BlogContext))]
    [Migration("20230906112245_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SomeByteFieldWithRange")
                        .HasColumnType("tinyint");

                    b.Property<float>("SomeFloatFieldWithRange")
                        .HasColumnType("real");

                    b.Property<int>("SomeIntFieldWithRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Posts", t =>
                        {
                            t.HasCheckConstraint("CK_Posts_SomeIntFieldWithRange_Range", "[SomeIntFieldWithRange] >= 0 AND [SomeIntFieldWithRange] <= 47");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
